name: Comment in Pull Request

on: pull_request

jobs:
  comment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Comment in PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: "Pull Request recebido."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
